/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdvisoryRouteImport } from './routes/_authenticated/advisory'
import { Route as AuthenticatedCloudRouteImport } from './routes/_authenticated/cloud'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFarmersRouteImport } from './routes/_authenticated/farmers'
import { Route as AuthenticatedFeedAnalysisRouteImport } from './routes/_authenticated/feed-analysis'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedNewTestRouteImport } from './routes/_authenticated/new-test'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSensorsRouteImport } from './routes/_authenticated/sensors'
import { Route as AuthenticatedSilageAnalysisRouteImport } from './routes/_authenticated/silage-analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdvisoryRoute = AuthenticatedAdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCloudRoute = AuthenticatedCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFarmersRoute = AuthenticatedFarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedAnalysisRoute =
  AuthenticatedFeedAnalysisRouteImport.update({
    id: '/feed-analysis',
    path: '/feed-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewTestRoute = AuthenticatedNewTestRouteImport.update({
  id: '/new-test',
  path: '/new-test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSensorsRoute = AuthenticatedSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSilageAnalysisRoute =
  AuthenticatedSilageAnalysisRouteImport.update({
    id: '/silage-analysis',
    path: '/silage-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisory': typeof AuthenticatedAdvisoryRoute
  '/cloud': typeof AuthenticatedCloudRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/farmers': typeof AuthenticatedFarmersRoute
  '/feed-analysis': typeof AuthenticatedFeedAnalysisRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/new-test': typeof AuthenticatedNewTestRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/silage-analysis': typeof AuthenticatedSilageAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisory': typeof AuthenticatedAdvisoryRoute
  '/cloud': typeof AuthenticatedCloudRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/farmers': typeof AuthenticatedFarmersRoute
  '/feed-analysis': typeof AuthenticatedFeedAnalysisRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/new-test': typeof AuthenticatedNewTestRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/silage-analysis': typeof AuthenticatedSilageAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/advisory': typeof AuthenticatedAdvisoryRoute
  '/_authenticated/cloud': typeof AuthenticatedCloudRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/farmers': typeof AuthenticatedFarmersRoute
  '/_authenticated/feed-analysis': typeof AuthenticatedFeedAnalysisRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/new-test': typeof AuthenticatedNewTestRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sensors': typeof AuthenticatedSensorsRoute
  '/_authenticated/silage-analysis': typeof AuthenticatedSilageAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisory'
    | '/cloud'
    | '/dashboard'
    | '/farmers'
    | '/feed-analysis'
    | '/history'
    | '/new-test'
    | '/reports'
    | '/sensors'
    | '/silage-analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisory'
    | '/cloud'
    | '/dashboard'
    | '/farmers'
    | '/feed-analysis'
    | '/history'
    | '/new-test'
    | '/reports'
    | '/sensors'
    | '/silage-analysis'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/advisory'
    | '/_authenticated/cloud'
    | '/_authenticated/dashboard'
    | '/_authenticated/farmers'
    | '/_authenticated/feed-analysis'
    | '/_authenticated/history'
    | '/_authenticated/new-test'
    | '/_authenticated/reports'
    | '/_authenticated/sensors'
    | '/_authenticated/silage-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/advisory': {
      id: '/_authenticated/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AuthenticatedAdvisoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cloud': {
      id: '/_authenticated/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof AuthenticatedCloudRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farmers': {
      id: '/_authenticated/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof AuthenticatedFarmersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed-analysis': {
      id: '/_authenticated/feed-analysis'
      path: '/feed-analysis'
      fullPath: '/feed-analysis'
      preLoaderRoute: typeof AuthenticatedFeedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-test': {
      id: '/_authenticated/new-test'
      path: '/new-test'
      fullPath: '/new-test'
      preLoaderRoute: typeof AuthenticatedNewTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sensors': {
      id: '/_authenticated/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof AuthenticatedSensorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/silage-analysis': {
      id: '/_authenticated/silage-analysis'
      path: '/silage-analysis'
      fullPath: '/silage-analysis'
      preLoaderRoute: typeof AuthenticatedSilageAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdvisoryRoute: typeof AuthenticatedAdvisoryRoute
  AuthenticatedCloudRoute: typeof AuthenticatedCloudRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFarmersRoute: typeof AuthenticatedFarmersRoute
  AuthenticatedFeedAnalysisRoute: typeof AuthenticatedFeedAnalysisRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedNewTestRoute: typeof AuthenticatedNewTestRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSensorsRoute: typeof AuthenticatedSensorsRoute
  AuthenticatedSilageAnalysisRoute: typeof AuthenticatedSilageAnalysisRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdvisoryRoute: AuthenticatedAdvisoryRoute,
  AuthenticatedCloudRoute: AuthenticatedCloudRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFarmersRoute: AuthenticatedFarmersRoute,
  AuthenticatedFeedAnalysisRoute: AuthenticatedFeedAnalysisRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedNewTestRoute: AuthenticatedNewTestRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSensorsRoute: AuthenticatedSensorsRoute,
  AuthenticatedSilageAnalysisRoute: AuthenticatedSilageAnalysisRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
